# Generated by Django 4.2 on 2023-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('image', models.ImageField(upload_to='ice_creams/')),
            ],
        ),
    ]
